spring.application.name=candidature
server.port=8085

spring.datasource.url=jdbc:h2:mem:candidaturedb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}